
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import mongoose from "mongoose";
const schema = new mongoose.Schema({"id":{"type":"string"},"owner":{"type":"string"},"approved":{"type":"string"},"tokenId":{"type":"string"},"blockNumber":{"type":"string"},"blockTimestamp":{"type":"string"},"transactionHash":{"type":"string"}});
export const ApprovalModel = mongoose.model('Approval', schema);
