// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEventConfig(ctx context.Context, arg CreateEventConfigParams) (EventConfig, error)
	CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error)
	DeleteEventConfig(ctx context.Context, id uuid.UUID) error
	DeleteNetwork(ctx context.Context, id uuid.UUID) error
	GetAllEventConfigs(ctx context.Context) ([]EventConfig, error)
	GetAllNetworks(ctx context.Context) ([]Network, error)
	GetEventConfigByContract(ctx context.Context, contract sql.NullString) ([]EventConfig, error)
	GetEventConfigByID(ctx context.Context, id uuid.UUID) (EventConfig, error)
	GetNetworkByID(ctx context.Context, id uuid.UUID) (Network, error)
	UpdateEventConfig(ctx context.Context, arg UpdateEventConfigParams) (EventConfig, error)
	UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (Network, error)
}

var _ Querier = (*Queries)(nil)
