config:
  - name: Meka
    source:
      address: "0x147923c03Ee14c65eaE13398926E35eA553cEA98"
      abi: Meka
      startBlock: 32228054
    entities:
      - Transfer
    eventHandlers:
      - event: Transfer(address,address,uint256)
        handler: handleTransfer
        file: handlers/meka/index.ts
        confirmations: 100
